"""Database models for The AI Exchange."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import JSON
from sqlmodel import Column, DateTime, Field, SQLModel, Text


class UserRole(str, Enum):
    """User roles."""

    STAFF = "STAFF"
    ADMIN = "ADMIN"


class ResourceType(str, Enum):
    """Resource content types."""

    REQUEST = "REQUEST"
    USE_CASE = "USE_CASE"
    PROMPT = "PROMPT"
    POLICY = "POLICY"


class ResourceStatus(str, Enum):
    """Resource status for requests."""

    OPEN = "OPEN"
    SOLVED = "SOLVED"


class User(SQLModel, table=True):
    """User model."""

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    email: str = Field(unique=True, index=True)
    hashed_password: str
    full_name: str
    role: UserRole = Field(default=UserRole.STAFF)
    is_active: bool = Field(default=True)
    is_approved: bool = Field(default=True)
    notification_prefs: dict[str, Any] = Field(
        default={
            "notify_requests": True,
            "notify_solutions": False,
        },
        sa_column=Column(JSON),
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True)),
    )

    def __repr__(self) -> str:
        """String representation."""
        return f"User(id={self.id}, email={self.email}, role={self.role})"


class Resource(SQLModel, table=True):
    """Resource model for requests, use cases, prompts, and policies."""

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="user.id", index=True)
    parent_id: Optional[UUID] = Field(
        default=None,
        foreign_key="resource.id",
        index=True,
        description="Parent request ID for solutions",
    )
    type: ResourceType = Field(index=True)
    status: ResourceStatus = Field(default=ResourceStatus.OPEN)
    title: str = Field(index=True)
    content_text: str = Field(sa_column=Column(Text))
    shadow_description: Optional[str] = Field(
        default=None,
        sa_column=Column(Text),
        description="Admin-provided improved description",
    )
    content_meta: dict[str, Any] = Field(
        default={},
        description="Flexible metadata (Model Used, Tools, etc.)",
        sa_column=Column(JSON),
    )
    is_anonymous: bool = Field(default=False, index=True)
    is_verified: bool = Field(default=False)
    is_hidden: bool = Field(default=False, index=True)
    system_tags: list[str] = Field(
        default=[],
        description="Auto-generated by YAKE + optional LLM",
        sa_column=Column(JSON),
    )
    user_tags: list[str] = Field(
        default=[],
        description="Manually added by author",
        sa_column=Column(JSON),
    )
    shadow_tags: list[str] = Field(
        default=[],
        description="Admin-provided tags",
        sa_column=Column(JSON),
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True), index=True),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True)),
    )

    def __repr__(self) -> str:
        """String representation."""
        return f"Resource(id={self.id}, type={self.type}, title={self.title})"

    @property
    def all_tags(self) -> list[str]:
        """Get all tags combined."""
        return list(set(self.system_tags + self.user_tags + self.shadow_tags))


class Subscription(SQLModel, table=True):
    """Subscription model for tag-based notifications."""

    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: UUID = Field(foreign_key="user.id", index=True)
    tag: str = Field(index=True)

    def __repr__(self) -> str:
        """String representation."""
        return f"Subscription(user_id={self.user_id}, tag={self.tag})"


# Response schemas (for API)
class UserBase(SQLModel):
    """Base user schema."""

    email: str
    full_name: str


class UserCreate(UserBase):
    """User creation schema."""

    password: str


class UserUpdate(SQLModel):
    """User update schema."""

    full_name: Optional[str] = None
    notification_prefs: Optional[dict] = None


class UserResponse(UserBase):
    """User response schema (without password)."""

    id: UUID
    role: UserRole
    is_active: bool
    is_approved: bool
    notification_prefs: dict[str, Any]
    created_at: datetime

    class Config:
        """Pydantic config."""

        from_attributes = True


class UserPublic(SQLModel):
    """Public user info (for anonymous masking)."""

    id: UUID
    full_name: str


class ResourceBase(SQLModel):
    """Base resource schema."""

    type: ResourceType
    title: str
    content_text: str
    is_anonymous: bool = False
    parent_id: Optional[UUID] = None
    content_meta: dict = Field(default={})


class ResourceCreate(ResourceBase):
    """Resource creation schema."""

    pass


class ResourceUpdate(SQLModel):
    """Resource update schema."""

    title: Optional[str] = None
    content_text: Optional[str] = None
    content_meta: Optional[dict] = None


class ResourceTagsUpdate(SQLModel):
    """Update tags for a resource (admin only)."""

    system_tags: Optional[list[str]] = None
    user_tags: Optional[list[str]] = None
    shadow_tags: Optional[list[str]] = None
    shadow_description: Optional[str] = None


class TagSuggestion(SQLModel):
    """Tag suggestions for user to choose from."""

    system_tags: list[str] = Field(description="YAKE + LLM suggestions")
    user_tags: list[str] = Field(default=[], description="User can add custom")


class ResourceResponse(ResourceBase):
    """Resource response schema."""

    id: UUID
    user_id: UUID
    status: ResourceStatus
    is_verified: bool
    is_hidden: bool
    system_tags: list[str]
    user_tags: list[str]
    shadow_tags: list[str]
    shadow_description: Optional[str]
    created_at: datetime
    updated_at: datetime

    class Config:
        """Pydantic config."""

        from_attributes = True


class ResourceWithAuthor(ResourceResponse):
    """Resource with author information."""

    author_name: str
    author_email: Optional[str] = None
    author_id: UUID


class SubscriptionCreate(SQLModel):
    """Subscription creation schema."""

    tag: str


class SubscriptionResponse(SQLModel):
    """Subscription response schema."""

    user_id: UUID
    tag: str

    class Config:
        """Pydantic config."""

        from_attributes = True
